version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    command: "npm run start"
  frontend:
    image: node:10.9.0
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "4200:4200"
    links:
      - "backend"
    command: "npm run docker-start"